# Site settings
title: mcaine.github.io
email: mikey.caine@btinternet.com
description: > # this means to ignore newlines until "baseurl:"
  Mike Caine's vanity site on github
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcaine.github.io" # the base hostname & protocol for your site
twitter_username: mikey_caine	
github_username:  mcaine

# Build settings
markdown: kramdown
highlighter: pygments